### ISSUE TITLE
Instructions not clear for me, explain better please

### ISSUE THREAD

**Issue by danylopez123** [Tarnadas/net64plus-server#1]
What i see is this:

    download and install Node
    git clone this repository or download as zip
    modify settings.json

But what i do with this node program + the downloaded server thing?

**Comment by Tarnadas** [comment]
I intentially only made a rough description of the steps to prevent flooding the server list with "unprofessionally" hosted servers, I'm sorry (no offense).
You can still use the exe for hosting a user server or try to find the answers yourself for hosting a dedicated server :)

**Comment by danylopez123** [comment]
Well, at least can you fix the link for this line: git clone this repository or download as zip ?

**Comment by Tarnadas** [comment]
You just have to google how git cloning works

**Comment by danylopez123** [comment]
Well i just did that, but everytime i start the thing, i get this:

0 info it worked if it ends with ok
1 verbose cli [ 'E:\\nodejs\\node.exe',
1 verbose cli   'E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle net64plus-server@2.0.2~prestart: net64plus-server@2.0.2
6 info lifecycle net64plus-server@2.0.2~start: net64plus-server@2.0.2
7 verbose lifecycle net64plus-server@2.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle net64plus-server@2.0.2~start: PATH: E:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Programas\Super_Mario_64_Online\net64plus-server\node_modules\.bin;C:\Users\Dani\bin;E:\Git\mingw64\bin;E:\Git\usr\local\bin;E:\Git\usr\bin;E:\Git\usr\bin;E:\Git\mingw64\bin;E:\Git\usr\bin;C:\Users\Dani\bin;E:\Oculus\Support\oculus-runtime;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Hewlett-Packard\SimplePass;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;E:\Panda3D-1.8.1\python;E:\Panda3D-1.8.1\bin;E:\Python27;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\MATLAB\MATLAB Compiler Runtime\v714\runtime\win64;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;E:\nodejs;E:\Git\cmd;C:\Users\Dani\AppData\Local\Microsoft\WindowsApps;E:\Dani\AppData\Roaming\npm;E:\Git\usr\bin\vendor_perl;E:\Git\usr\bin\core_perl
9 verbose lifecycle net64plus-server@2.0.2~start: CWD: E:\Programas\Super_Mario_64_Online\net64plus-server
10 silly lifecycle net64plus-server@2.0.2~start: Args: [ '/d /s /c', 'node ./dist/' ]
11 silly lifecycle net64plus-server@2.0.2~start: Returned: code: 1  signal: null
12 info lifecycle net64plus-server@2.0.2~start: Failed to exec start script
13 verbose stack Error: net64plus-server@2.0.2 start: `node ./dist/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (E:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid net64plus-server@2.0.2
15 verbose cwd E:\Programas\Super_Mario_64_Online\net64plus-server
16 verbose Windows_NT 10.0.16299
17 verbose argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error net64plus-server@2.0.2 start: `node ./dist/`
22 error Exit status 1
23 error Failed at the net64plus-server@2.0.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by computernewb** [comment]
> I intentially only made a rough description of the steps to prevent flooding the server list with "unprofessionally" hosted servers, I'm sorry (no offense).

Sorry, but it just seems silly to me to intentionally cripple your documentation just to prevent some "noobs" from hosting a Net64+ server. 

Anyway to OP: What OS are you running?

**Comment by danylopez123** [comment]
Windows 10
