### ISSUE TITLE
Erros on startup

### ISSUE THREAD

**Issue by Kanuuu** [Tarnadas/net64plus-server#25]
On linux debian 9.7 i got problems to start the server.
Tested with npm 8 and npm 11, also with version 2.2.2

[at-loader] Checking finished with 8 errors
Hash: a205a4ed1b8b7a427140
Version: webpack 3.12.0
Child
    Hash: a205a4ed1b8b7a427140
    Time: 18648ms
       Asset     Size  Chunks                    Chunk Names
    index.js  1.11 MB       0  [emitted]  [big]  main
       [0] ./src/globals.ts 285 bytes {0} [built]
       [1] ./src/proto/ServerClientMessage.js 220 kB {0} [built]
       [5] ./src/models/Connection.model.ts 354 bytes {0} [built]
       [6] ./src/models/Settings.model.ts 475 bytes {0} [built]
       [7] ./src/index.ts 2.4 kB {0} [built]
       [8] ./src/WebSocketServer.ts 14.6 kB {0} [built]
       [9] ./src/Client.ts 19.1 kB {0} [built]
      [10] ./src/Identity.ts 7.25 kB {0} [built]
      [11] ./src/Player.ts 1.19 kB {0} [built]
      [13] ./src/proto/ClientServerMessage.js 127 kB {0} [built]
      [16] ./src/MetaData.ts 1.17 kB {0} [built]
      [18] ./src/Command.ts 10.2 kB {0} [built]
      [19] ./src/Vote.ts 2.45 kB {0} [built]
      [21] ./src/WebHook.ts 2.5 kB {0} [built]
      [22] ./src/Arguments.ts 2.67 kB {0} [built]
        + 11 hidden modules

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:27:10
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:28:11
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:29:10
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:30:12
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:31:13
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:32:11
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:33:14
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.

    ERROR in [at-loader] ./node_modules/jest-mock-axios/dist/lib/mock-axios-type                                                                                                                                                             s.d.ts:35:13
        TS2707: Generic type 'Mock<T>' requires between 0 and 1 type arguments.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! net64plus-server@2.2.2 build:dev: `webpack --env=dev`
npm ERR! Exit status 2
npm ERR!

**Comment by Tarnadas** [comment]
Delete all your node_modules. Then use yarn to install depenendies instead of npm

**Comment by Tarnadas** [comment]
I assume this fixed your issue, so I will close this
