### ISSUE TITLE
De-obfuscated server executable?

### ISSUE THREAD

**Issue by khyber-pass-arms-dealer** [Tarnadas/net64plus-server#3]
Suppose i know Javascript (I do) and wanted to modify the server's code (eg. to add custom commands and such),  is there a de-obfuscated version of the server executable or another way i may add this sort of functionality? Since the server controls the chat, it should be possible to implement all sorts of server-side plugins, much like what was done with many minecraft servers.

**Comment by BPopcorn** [comment]
Just clone the repo. You can modify the code and then recompile it. Where's the problem?

**Comment by khyber-pass-arms-dealer** [comment]
The problem lies in dist/index.js, as whoever has written the code has used some sort of obfuscation tool to make it unreadable, so I technically can edit it, but wouldn't do any good.

**Comment by Tarnadas** [comment]
I obfuscated the code for the potential need of higher security in future releases.

I'd rather like to create a plug-in system instead of re-open sourcing the code (1.x) was OS).

**Comment by khyber-pass-arms-dealer** [comment]
I'm highly interested in this plug-in system, i'll definitely keep an eye out for it.

**Comment by DizzyThermal** [comment]
My vote is for a plugin system over obfuscation.

Many times obfuscation leads to people investing copious amounts of time into cracking it.. This will become a cat-and-mouse game.

I personally won't run code on my server that I don't have the source to.
