### ISSUE TITLE
ERR: NO SCRIPT

### ISSUE THREAD

**Issue by Jackknife18846** [Tarnadas/net64plus-server#4]
I'm trying to host my own server with auto restarts as you showed, but when I do $ npm run build I always get this: 
npm ERR! missing script: build
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jack\AppData\Roaming\npm-cache\_logs\2018-05-16T21_35_28_387Z-debug.log

**Comment by DizzyThermal** [comment]
Did you run npm build first?

This issue doesn't provide sufficient information to debug. Please provide more context on what you're trying to do.

**Comment by Xhizors24** [comment]
It is working. Just use $ npm run start
This happens because line 7 in packages.json is named start instead of build.

**Comment by Tarnadas** [comment]
Yeah there is no more build script, because it's already built. Just skip it.
I updated the readme
